### PR TITLE
Array container

### PR DESCRIPTION
**Pull request by giosava94**
Hi,
here it is a new base component with its documentation and examples: ArrayContainer.

This components has been designed to work with waveform PVs. It uses the Widget logic and, based on the length of the array (PV value) or a custom length decided by the user, it instantiates a baseComponent for each value. 

Let's make an example to explain it better: if users want to associate to each array element a **TextInput**, they need to pass to the _component_ prop the **TextInputComponent** (the inner component of **TextInput**); the **ArrayContainer** will create, for each array element, a **TextInputComponent**. In fact it is the **ArrayContainer** that establishes the connection with the PV, whereas each element should use only the graphic behavior of the **TextInput**. This way we can reuse the already implemented code and it will up to date if those components will change.
**ArrayContainer** forwards all props (and children) to the component received from _component_ prop.
In the styleguide there is a set of different examples.

The following changes to the existing components were required:
- All BaseComponents (except for the deprecated ones, Graphs and TextUpdateMultiplePVs) must export the inner component with the graphic logic. I added named exports and kept the unnamed export; this way the styleguide works as before. Moreover I changed all _withStyles_ logic with _makeStyles_ and _useTheme_ to simplify the export logic (no side effects detect, everything works as before).
- Widget has been lightly modified. When reading arrays, (for example) if the _numberFormat_ props was enabled, the input array was truncated to the first value. In order to overcome this issue I added a check over the received value to detect if it is an array; if so the logic applies the operation/convertion to all the array elements.

Both older components and new one works fine.

The ArrayContainer can receives custom components (not baseComponents) as inputs for the **component** prop. It is not intended to be used with the RadioButtonGroup, SelectionList and SelectionInput components which are designed for mbbo/mbbi PVs.

When you have time, let me know what you think about it.

Regards,
Giovanni

### CODE REVIEW

**Comment by wduckitt** [comment]
Hi

I take it this component is used to read out an array of registers? And instead of mapping each register to an individual record you bring out the whole array and do it in the frontend.

1. I wondering if this component should sit in a different folder? And then the documentation needs a better explenation of wht we are trying to achieve with a diagram?
2. Perhaps the suffix Component should  become Base. i.e it should become TextInputBase?
3. Perhaps the prop number of elements is limiting and maybe we should make it an index array ie [1,3,6] would display the 1st, 3rd and 6th element. In this case you can also view different elements of the array with as textinputs or led for example.

4. After writing this I am wondering if there is not a simpler way to do it? Instead of modifying every component we modify the PV component to detect for square brackets at the end of the pv pame[], and then return the scalar value of the array element and only write to that element for writable components, YES i think this is the way to go. We can also then  add in a bit addressing at the same time.

in this way we just use a map function 
const test=(props)=>{
let registers1 = [1,3,6]

return (
<div>
{registers.map((item,index)=>(
     <TextInput
        key={index.toString()}
         pv={"pva://testIOC:test4["+item+"]"}
         usePvLabel={true}
     />
      ))}
</div>
}


Let me know what you think.

**Comment by giosava94** [comment]
Hi,

this component is meant to read WAVEFORM PV and not multiple PVs.

Suppose the received PV is the following

record(waveform, "myWaveform") {
    field(DESC, "Waveform PV")
    field(NELM, "10")
}

and suppose that, after a caput or a proper initialization, the value of this pv is an array with the following values

[1, 5, 3, -1, 6, 7, 0.1, 23, -1.4, 10000]

due to the fact that the PV is only one but I want a TextInput for each value (because I want to edit each value independently), currently the ArrayContainer will connect to the PV and will create a TextInputComponent component for each value of the array because I don't want to establish multiple connection to the same PV but only reuse the logic used for the TextInput.

I am trying to emulate the Array CS-Studio widget. Is it clear?

Now I will respond to your points

1 - Maybe the component can go into another folder. I will update the documentation (also with a diagram) after we will have both clear this widget's behavior.

2 - Currently in each BaseComponent the suffix is "Component", change it to "Base" or only export it as "Base" its not a problem form me. I agree about "Component" being quite uneasy to use (also for explanations). Other alternatives can be "Core", "Content"...  Choose the one you prefer.

3 - I can substitute the numberOfElements with this new props to map a specific set of value from the array as you suggested. 

4 - Currently some BaseComponents already have a default behavior when receiving a waveform PV (for example TextInput, if not specifying the numberFormat props, already show in a unique TextField all the array values) for this reason I did not directly modified those components but I created a new one. If you say we can change this behavior for me there are no problems but I don't know if other users already use this feature.
The solution to change the PV, or the Widget, component maybe it's a better solution. Actually I don't know if your solution to create multiple TextInput is more efficient. With this solution you are adding multiple client to the same python room and you are creating more TextInputs which are more complex than the TextInputComponents because they are based on Widget which is particularly complex; moreover the ContextMenu can have strange behavior and the map function (independently on the fact you want to map only a subset of registers) is always needed, for this reason it can be directly implemented inside the component and can be hidden to the user. 
Maybe we can change the Widget component so that the TextInput automatically creates multiple TextInputComponent based on the value's type (array or not) and the props described before (numberOfElements, "offset", "map/arrayIndex/registers"). I will try those solutions and I will let you know which is more user friendly and efficient.

**Comment by wduckitt** [comment]
Hi

Yes, I had also used the CSS array to read out an array of registers
inside a highspeed DAC via its SPI bus.

It is a handy feature to have.

I don't want to get into a situation where we have to modify every
component to just to display an array for isolated use cases.
In these types of cases I feel it is better to discuss what needs to be
done before all the components and the widget are modified. We just went
through a major rewrite in moving to the hooks and the widget, and can't
afford to evaluate pull requests that affect all components and complicate
the future writing of new components for an isolated use case.

I don't think the PV component mod I propose will cause a performance
issue. pvServer pvinfo requests to the same pv are serviced on a polled
rate, only 1 ca connection is made to the pv, so if multiple requests come
in then they should get serviced in the next cycle or when the initial ca
connection call back occurs and perhaps only one sockeio emit event to the
pv room will occur.

On the react side each pv connection will listen on the same single event,
and extract the scalar value from the Array and then update the
corresponding basecomponent.

I'll implement it on different barch and get back to you.
Regards,

William

The pvserver

**Comment by giosava94** [comment]
I didn't intend to edit each BaseComponent logic.

In these new commits (1 hour ago) I had integrated the ArrayContainer logic in the Widget component. This way every new custom widget will benefit this change without changing the BaseComponents. 

The only changes in the BaseComponents are the ones related to the props definition for the styleguide.

Take a look before starting your branch.

**Comment by wduckitt** [comment]
Ok I had a quick look at the widget.js, I like your new suggestion. Its going to take a bit of time evaluate propperly. I'll get back to I can

**Comment by wduckitt** [comment]
I dont like the additional props added to each component, they will create to much confusion for the default use cases, we need a different plan.

**Comment by giosava94** [comment]
Ok, glad to here it can be a good starting point.
Take your time to evaluate an alternative for the props replication on the base components, or another alternative. 
I'll think about it too.

**Comment by wduckitt** [comment]
Perhaps a higher order component will  work that passes the props into the component?
The prop defintions should be in the widget.js and the Array container, but not in the component, because they are not used in the componet itself.
Please implement just for the TextInput and TextUpdate for now and then we take a look.

Usage as below:
```
<ArrayContainer
pv={"pva://waverorm"}
component={TextInput}
registers={[1,2, 5]}
registersLabel={["one","two","five"]}
registersLabelPlacement={"top"}
alignHorizontal={true}
 />
```

**Comment by giosava94** [comment]
I don't understand what behavior you desire.

With the last change Widget completely replace ArrayContainer.

Now, what you want, is: 
To use ArrayContainer, editing it, so that users use this component to create "Array of BaseComponents" but keep the "array creation logic" inside the Widget component?
This way you can add the ArrayContainer to the styleguide with the correct props (and leave the BaseComponents as they are)?

Did I correctly understand what you mean?

**Comment by wduckitt** [comment]
Yes , keep the logic in the widget.js, And use the ArrayContainer simply to pass on the props and show the prop definitions in the styleguide.

**Comment by wduckitt** [comment]
Hi I had a look at the last commit and this now more inline with what I can accept with the final pull request.

For  now can I please ask that you simplify the changes in the pull request, to only the Widget.js and the addtion of the ArrayContainer.
Can you  move the ArrayContainer to a new folder called CompoundComponents, which would require an new entry in the styleguide below the base components.

I can accept changes to all base components with respect to the basecomponents and the makeStyles as a maintenance pull request when I have time to evaluate them properly.

**Comment by giosava94** [comment]
Hi,

Adding the ArrayContainer just for documentation purposes is redundant in my opinion because we are suggesting users to use a component which actually is not required. Each BaseComponent already works as an arrayContainer

If the problem is the documentation organization I thought that another solution could be the possibility to edit the main page of the BaseComponents documentation (http://127.0.0.1:6060/#/Style%20Guide/Base%20Components) so that we give a description about this feature (array of BaseComponent when a waveform PV is received) and we display the "common props" to control this feature. The only file to change is `workingWwithComponents.md` adding a description of how it works and a table with the possible props (as you did in `Widget.md`).

What do you think? (The ArrayComponent can already be removed)

**Comment by wduckitt** [comment]
The problem comes from the style guide not being able to section props for
specific functions.

ArrayContainer is an isolated use case, like i said yesterday, none of the
extra props effect the normal operation of the component, and they get
ordered alphabetically in the styleguide. I feel the ArrayContainer wrapper
component solution will  isolate the props documentation, and with the
correct introduction to the ArrayContainer explain the use case.

Please formulate the pull request like this and then we can merge it.

**Comment by wduckitt** [comment]
Hi Giovanni 

Have you made any progess as I requested in my previous comment?

Regards,

William

**Comment by giosava94** [comment]
Hello William,

In this time I re-evalauted the idea to wrap the `BaseComponent` itself inside the `ArrayContainer` instead editing Widget.js.
I explain.

The `ArrayContainer` objectives are:

- Show each element of a waveform PV as independent `BaseComponent`.
- Keep the BaseComponents as they are. Both documentation and logic.
- Users should use the `ArrayContainer` component to enable this feature.
- Create a separate section in the documentation explaining how to use this component.

The current development situation is:

- Start again from V2.0.0. Changes belonging to more recent versions do not introduce errors or conflicts. I already successfully execute a merge of version V2.1.0.
- Create the component `ArrayContainer`. This component has its own props and can receive multiple BaseComponents as children.
- Edit `Widget`. When `Widget` receives the **index** prop, and the PV value is an array, the component updates and shows only **value[index]**.
- The `ArrayContainer` re-creates, for each `BaseComponent` received as a child, the same `BaseComponent` adding to them the additional prop **index**.
- Kept the **registers** and **registersLabel** props as we previously discussed and add other props related to display behavior.
- Users can decide to show only a subset of the array values through the **visibleItemsCount** prop. In this case `ArrayContainer` will renders only the `BaseComponents` related to those indexes. With the mouse wheel users can scroll and see the other values. This feature will prevent heavy useless renderizations (it's no use to show an array of 100 elements if in the screen you can see at most 20 elements, but if users want it they can obtain this behavior setting the correct props values).
- Add documentation about the possible props the `ArrayContainer` can receive in the `CompoundComponents` section.

Current issues:

- The `ArrayContainer` does not _extends_ the `Widget` component as, for example, `TextInput` does. For this reason it does know nothing about the length of the array stored in the PV. Users must set the correct size through the **maxItemsCount** or **registers** props. When the `ArrayContainer` sends an index value that is outside the array bounds the corresponding `BaseComponent` appears disconnected.
- It works well with PVs that do not change or changes due to a user update. When the input PV updates too frequently, for example the _IOCtest:test4_ in the _demoIOC_, the pages slows down too much. I think that this problem is related to a lower level of the **PV connection stack**. A similar problem happens in other interfaces with a lot of active connections.
- BaseComponents wrapped inside a Grid item or a Grid container can't receive the **index** prop.

Example:

    <ArrayContainer>
        <TextInput />
    </ArrayContainer>

TextInput can receive all its standard props.

These are the major details. What do you think?

PS. The only relevant change applied to `Widget` is the introduction of the index prop. In a few days I will upload the changes.

**Comment by giosava94** [comment]
I merged **V2.0.1** into **arrayContainer** in order to be up to date. Then I merged the changes applied to the `ArrayContainer` component.

I had to change the functions managing the values read from and written to the PVs because the *format* and the *parseFloat* function, applied to arrays, returned only the first value of the array.

I exported the functions into another file (to light up the `Widget.js` component and to let those functions available to other components) and applied some changes in order to execute the said functions for all the elements of the array.

All the BaseComponents are unchanged.

**Comment by wduckitt** [comment]
Its in the 2.2RC branch

**Pull request closed without merging**
