### PR TITLE
Integer arrays cause JSON formatting exception

### PR DESCRIPTION
**Pull request by hanak**
**Problem**
When FTVP is LONG and length of the type (field NORD is 0), a JSON exception is raised:
_Exception: Object of type c_long_Array_0 is not JSON serializable_

**Analysis**
If the PV is an array, pyepics will supply an instance of ctype class representing an array (e.g. epics.dbr.c_double_Array_500). Yet, ctype class types do not support JSON serialization. Therefore, the pvServer attempts to work around this by converting to a Python array explicitly. However, if the array length is 0, the pvServer will run the conversion only if the type is double even though EPICS supports other data types.

**Solution**
* Convert to an empty array if the there are 0 elements in the array regardless the type.
* Report an exception to console in order to simplify troubleshooting defects which may happen in runtime. Since these exceptions are not meant to happen during usual use, we can afford dumping extended information to the logs.

**Test**
* Create a PV variable (record type waveform, FTVL="LONG"). Put zero-length array into it. Access through pvServer. Verify no exception reports appears in the console.

**Question to Owners of the React Automation Studio**
I am removing the trailing white space prior commits automatically. Thus, I had to restore the white space back manually prior creating this pull request. Can I remove all trailing spaces in the file pvServer.py in the scope of this pull request?

### CODE REVIEW

**Comment by hanak** [comment]
Dear Sir,

I have create this pull request as a result of my use of the React Automation Studio (RAS). I think RAS is a great idea and it helped me to create UI which looks modern and which is likely to run on various devices. Thank you for it. Would it be possible to review this pull-request, please?

Thank you.

Sincerely,
Ivo Hanak

**Comment by wduckitt** [comment]
Hi Ivo, 

Thanks for the complement. 
I thought we had caught all the quirks  for pyepics and json non serializble. This is first one since the initial release.

I will take a look at this  in a week or so time, as we have  holidays coming up. Can I ask you attach an epics record for this scenario that so that I can add a pv into the demo ioc as a test variable.

**Comment by hanak** [comment]
A record which can trigger the exception:
```
record(waveform, "longArray") {
  field(NELM, "10")
  field(FTVL, "LONG")
}
```

**Review by wduckitt — APPROVED** [review]

**Comment by wduckitt** [comment]
merged and updated to V2.0.1

**Pull request merged**
