### PR TITLE
Logging through python logger

### PR DESCRIPTION
**Pull request by hanak**
**This pull request includes the pull request #8 and #10.** This is a result of an attempt to avoid creating a huge pull request while still being able to use the changes together without additional manual merging. I would suggest to review after #8 and #10.

**Problem**
pvServer logs to console using print. As a consequence, time of the log is not captured, redirection to a file is possible only through redirecting console output, log level is controlled using comments. At the same time, Python includes a logging library which can offer these capabilities.

**Solution**
* Added a module "log" which forwards logs to the package logging and which allows controlling the logging level through environment variables. Default log level is INFO. Log output si directed to console.
* Converted relevant calls to print() which are not commented out into log.info(). If appropriate other log levels were used.

**Visible Changes**
Logs printed into console include time and log level. If this breaks existing log parsers, the solution can be modified so that logging to the console will include this info only when requested.

**Test**
Run pvServer. This test is not really adequate because it does not test all code routes. Thus, I cannot rule out we will not see new defects.

### CODE REVIEW

**Comment by wduckitt** [comment]
I had a good look. At first look the logger looks great, but I noticed that it blocks the main thread. So if you have two user interfaces open on the mobile demo1  and you refresh the one and it creates an info log then the other user interface stops updating for brief moment.

I tried this with filename declared and undeclared. So there is no difference if it logs to the strema or a file.

Can you try an implement a non blocking logger? 

PS I can make the change for the zero length integer array but i will have to undo all the commits for the logger Or can you just submit a pull request for those 3 lines of code?

**Comment by hanak** [comment]
Thank you for your review.

Regarding the change for the zero array. The plan I was aiming for was to update this pull request once the #8 is in the master. I just included #8 (and #10) here so that I am can run the application (which needs #8) while working on the loggers. I did not intent to cherry-pick #8 or #10 from this branch. I will update this pull request once #8 (or #10) is in.

Regarding the non-blocking logger.
* I will try to my luck searching for a package first. I would assume we are not the first project which might be running into it. Would this (i.e. a new dependency) be acceptable for you? If I am not not that lucky, I can add a thread.
* It is interesting to see a noticeable delay due to one message especially considering the chain the data has to pass through before showing up at the screen. It is kind of tempting to collect some statistics around response time (of the pvServer) to get some impression how busy the server is and how quick it responds. Maybe, this can be enabled when the logging level is set to "DEBUG". I am not able to promise much (due to limited time I can spend on it) but it is tempting. What do you think?
* Do you run any automated tests which would help us to see the potential impact of the logging in numbers?

**Comment by wduckitt** [comment]
Perhaps this can guide you:
https://docs.python.org/3/howto/logging-cookbook.html#dealing-with-handlers-that-block

Yes an alternative package is fine.
It appears to delay processing by about 1 second. Which is strange from a
logging implementation, and perhaps you would only notice it in a real time
PWA like RAS. I had a real world setup where the client makes a connection
to 1600 PVs on actual hardware,  and there is no performance degradation to
other clients connected to the demos. I had an idea to bring server
statistics  to the client as a widget. I'll try implement it when i am done
with the archiver viewer.
Currently only the demos and the styleguide serve as a test.

**Comment by hanak** [comment]
Thank you for your response and further details. I have tried to recreate the problem. I did following steps:
1) Start testIOC, start pvServer, start the React application using a development server (npm start)
2) Open MobileDemo1 in one browser. This is the user 1.
3) Open MobileDemo1 in other browser. This is the user 2.
4) Refresh MobileDemo1 (CTR+F5)
Does it match your sequence of steps?

According to your description, the user 1 should experience significant lag (around a second). Unfortunately, I was not able to observe it. What if you add a log message right after "Client Connected"? Does the console show the second log happens one second after the other?

In order to see the impact of logging, I have added an info log message in pvServer.py inside a function onValueChanges (line 254):
`log.info('PV [{}] has changed', pvname1)`
If every such a log message caused a significant lag, it would make everything unusable as PVs change quite often in the demo application. After running the pvServer, console showed following:
image

And, the UI did not feel frozen or lagging. Could you try to pul the log message to the pvServer, please? I am curious what you would observe.

My configuration:
* Windows 10
* Python 3.8.2 (32-bit)
* EPICS base 7.0.3.1
* IOC built for windows-x64
* Docker not used (I would not expect any impact but just to get the picture complete)
* Browser: Firefox (the user 1) and Edge (the user 2)

Also, I have added following changes:
* log.py: exception log function. This is useful when logging exception inside an exception handler. It will log the exception including stack trace.
* .gitignore: Ignore EPICS build folders regardless EPICS_HOST_ARCH. Ignore epics/testIOC/RELEASE.local. Ignore ReactApp/node_modules

Changes which I did not include:
* `testIOC/include/xxxRecord.h`: The build added a file BKLNK. I am not sure when this field appeared in EPICS. It looks like discussions around EPICS 7.0.2.1 referenced to this field as new (https://epics.anl.gov/core-talk/2019/msg00392.php). Since `xxxRecord.h` is generated by the build, should it be included in the source control?
* `package.json`: This file updated after running NPM. It removed blank lines and it add a space after ":" on a few lines. Should I include `package.json` in the changes?

I am not trying to object the idea of adding a non-blocking log. I am just trying to find out more as a lag of almost a second sounds really strange. And, it is not clear to me what the source would be considering the current hardware.

**Comment by wduckitt** [comment]
I was looking into this now again, it might be my bad. I experience a lag
on refresh on chrome when duplicating a window on my linux  pc. It
doesn't appear to be log related.

**Comment by hanak** [comment]
Thank you for confirmation. I have added the non-blocking logger using recommendation you have suggested earlier:
https://docs.python.org/3/howto/logging-cookbook.html#dealing-with-handlers-that-block

In addition to this:
* Log setting is printed explicitly because the logger may use defaults.
* Log file will truncate if the log size reaches predefined size. Prior truncating, a backup of the log file will be created. Both maximum size (default is 16 MB) and the number of backups (default is 2) can be controlled through optional environment variables.

The only problematic observation I made while testing is that gevent will raise an exception twice on CTR+C inside a handler of KeyboardInterrupt:
```
During the call to 'onerror', another exception occurred:
...
handle = tb.tb_frame.f_locals['handle'] if tb is not None else None
KeyError: 'handle'
```
This might cause a gevent popup to appear on Windows. Since this is something new to me I will try to see what caused it.

**Comment by hanak** [comment]
According to source of gevent, `unhandled_onerror` (in which the problem occurs) is supposed to be used for signals. And, it looks like an update to gevent (https://github.com/gevent/gevent/commit/e64647fe5ebc44eaf9b00ab4dc570898f3d9b2db) corrected the like which causes `KeyError` (current line: `handle = tb.tb_frame.f_locals.get('handle') if tb is not None else None`). It looks like the fix should be available in gevent (1.5.0+).

Still, this not does answer the question on why I have not seen this before (at least I do not recall it). Unfortunately, even if I remove the logger, I am still seeing it. Have you observed anything similar?

**Comment by hanak** [comment]
I missed a use case while testing. I am sorry.

**Comment by wduckitt** [comment]
I have changed the environment variable names and have also added a default
filename name that is mapped as a volume to the container via the compose
files.

Please have a look at the hanak-logging-through-python-logger
<https://github.com/wduckitt/React-Automation-Studio/tree/hanak-logging-through-python-logger>
  branch.

Let me know if you have any questions.

**Comment by hanak** [comment]
Thank you for the update. Environmental variable names look good. The settings in docker-compose-dev look good, too.

**Comment by wduckitt** [comment]
Ok  i have merged and update the release to V2.0.1

**Pull request merged**
