### PR TITLE
useContextMenu hook

### PR DESCRIPTION
**Pull request by giosava94**
Hello,

I noticed that, in some cases, the `ContextMenu` does not show in the correct place (sometimes it appears at the bottom center of the page). 
In order to resolve this minor random bug I edited the `ContextMenu` anchoring logic.
Now it uses the x and y mouse event coordinates and the error does not happens anymore.

Another issue I found, related to the `ContextMenu`, was in the **useEffect** in charge of updating the `ContextMenu` pvs.
It was executed every time the value in **pv** or in the **pvs** changed also when the `ContextMenu` was closed.
When having multiple PVs connected to the same widget this can reduce the performances and can be a waste of resources (mostly when there are a lot of widgets in the page).
My proposed solution is to calculate the `ContextMenu` pvs only when opening the `ContextMenu`.

In the end I extracted all the logic connected to the `ContextMenu` (open/close, positioning and PV list creation) into a custom hook called `useContextMenu`.
This way the `ContextMenu` logic can be completely used also in other components if needed (and with respect to its requirements) and the `Widget` component is a bit more readable.

Hope this will help,
regards
Giovanni

### CODE REVIEW

**Comment by giosava94** [comment]
Sorry I checked again the code and there are still some bugs at a lower level.
Don't merge this pull request. I'm closing it.

**Comment by giosava94** [comment]
Hi, 
When opening the contextMenu of a component and then quickly double-clicking again in another point of the page, the current contextMenu reopen in that new point. I decide to render the contextMenu only when it should be opened. This solution avoid also some unused renderization that is still active when the component is mounted but not visible.

**Comment by wduckitt** [comment]
Hi, 
Im busy with the 2.2RC branch. After merging the ArrayContainer there are too many merge conflicts. If you have time to correct it against 2.2RC then I can merge it, otherwise it can go in on later version after you have fixed the new conflicts.

**Comment by giosava94** [comment]
Hi william,
I merged the **2.2RC** branch into the pull request e resolved conflicts

**Comment by wduckitt** [comment]
Thanks, I have merge it into 2.2RC

**Pull request closed without merging**
